### ISSUE TITLE
Sometimes Radarr or Sonarr can't  import due to looking for folder with exact same name as file

### ISSUE THREAD

**Issue by minus1kelvin** [rogerfar/rdt-client#63] opened 2021-05-21 12:03 UTC
I  have this issue, but only on occasion and not consistently in both Sonarr and Radarr:

When a file is downloaded it is located in a folder that was created in my sonarr or radarr subfolders. It is usually named very similar to the folder but not exactly. This is often not a problem for imports but sometimes this happens:

Import failed, path does not exist or is not accessible by Radarr: /xxxxxxxxx/radarr/NAMEOFFILE.mkv/. Ensure the path exists and the user running Radarr has the correct permissions to access this file/folder

My problem is that Radarr is looking for a FOLDER with the name the file. If I change the folder to be the EXACT SAME name as the file (including the file extension) then it finds the file. In this case, the example above, I have a file named NAMEOFFILE.mkv. If I change the folder the file is in to be named NAMEOFFILE.mkv, then the import will proceed. This doesn't happen all the time, but it happens enough to where I have a python script I can run that will change the name of the folder to the file name of the file inside the folder to fix the issue.

Any ideas? Thanks!

**Comment by rogerfar** [comment] 2021-05-22 20:45
Are you running the latest version? There was an issue that newer torrents would get renamed in RealDebrid, thus the path was wrong when downloaded. But this should have been fixed a while ago already.

**Comment by minus1kelvin** [comment] 2021-05-22 20:51
> Are you running the latest version? There was an issue that newer torrents would get renamed in RealDebrid, thus the path was wrong when downloaded. But this should have been fixed a while ago already.

Just double checked, yup running 1.7.4

**Comment by bal8784** [comment] 2021-05-27 17:53
Same happening here, im on 1.7.4 also

Error|DownloadedEpisodesImportService|Import failed, path does not exist or is not accessible by Sonarr: /downloads/sonarr/A.Million.Little.Things.S03E15.720p.WEB.H264-STRONTiUM.mkv/. Ensure the path exists and the user running Sonarr has the correct permissions to access this file/folder

If i rename the actual directy to above, sonarr imports successfully. Happens on a variety of different shows but not all.

**Comment by rogerfar** [comment] 2021-05-27 19:07
Does it consistently happen with the same torrent? If so can you send it to me through a pastebin?

**Comment by bal8784** [comment] 2021-05-27 23:06
I want to say it works intermittently with the same torrent...I downloaded it a few more times and it was always creating the XXXX.mkv/ directory. However, while I was doing this sonarr was being wonky, I think because the torrent got placed in the blacklist.

I tried a different torrent(to see if sonarr was still being wonky) for the same show and it created a directory named 'XXXXX[rarbg]' and it downloaded and imported correctly.

Next time it happens I'll capture the logs and attempt a retry with the same torrent again.

**Comment by timcoop3r** [comment] 2021-05-31 10:27
Fwiw, I see this pretty regularly as well.

**Comment by timcoop3r** [comment] 2021-06-04 12:47
It looks like the folder name is perhaps created incorrectly? Looking at the qbt API endpoint created by rdt-client, the 'content_path' matches the torrent 'name', but the folder created strips the file extension present in the name. (At least the name shown)

Either that, or the file extension inside the torrent is getting added to the torrent name somewhere after folder creation?

I expect this happens pretty much every time with single file torrents for me to be honest, so should be pretty reproducible?

**Comment by rogerfar** [comment] 2021-06-05 16:41
I ran in this again now as well, but first time since a few weeks... 

What I think happens is that the torrent somehow gets renamed along the way, that's why it's almost impossible to reproduce because as soon as RDT has the torrent, it won't rename it again.

I think I'll do 2 things: as soon as it has a torrent name, never rename it again, and force the extra path to use the torrent name, not the name of the downloaded RAR file.

Would what work?

**Comment by rogerfar** [comment] 2021-06-05 17:47
Actually I think I see it now, there's another property in the API for OriginalFileName which was used wrongly before, on the next release this should be fixed.

**Comment by rogerfar** [comment] 2021-06-05 21:01
This is fixed in 1.7.6

**Closed by rogerfar** 2021-06-05 21:01 UTC
