### ISSUE TITLE
[BUG] [HUGE] Memery Leak

### ISSUE THREAD

**Issue by AnCasper** [rogerfar/rdt-client#558] opened 2024-08-04 14:39 UTC
**What version are you using?**
2.0.81

**Wat OS are you running?**
Windows 11 - 10.0.22631 Build 22631

**Are you using Docker or as a service?**
Service

**Which debrid provider are you using?**
Real-Debrid

**Which downloader are you using?**
Internal-Downloader

**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/user-attachments/files/16487936/rdtclient.log)

**Screenshots**
![ORM-errors](https://github.com/user-attachments/assets/0bbf5a97-0717-42fb-83a1-13b60bc8eeda)
![new-guard-error](https://github.com/user-attachments/assets/23ab9150-bca3-4ccf-b4b3-1f35999677a4)

**NOTE** Can this run through a VPN? rewason for asking is because the traffic on the VPN does not get touched.

**Comment by rogerfar** [comment] 2024-08-04 15:01
Duplicate of https://github.com/rogerfar/rdt-client/issues/509

**Closed by rogerfar** 2024-08-04 15:01 UTC
