### ISSUE TITLE
Reverse proxy base URL doesn't set for main page

### ISSUE THREAD

**Issue by drmikecrowe** [rogerfar/rdt-client#177] opened 2022-08-28 16:52 UTC
**What version are you using?**
Version 2.0.17

**What OS are you running?**
Linux

**Are you using Docker or as a service?**
Yes

**Please attach a log file here with the log setting set to debug**
```log
[12:48:48 DBG] Updating torrent info from Real-Debrid
[12:48:50 DBG] Finished updating torrent info from Real-Debrid, next update in 10 seconds
```

When using a reverse proxy and setting the path to `/rdtclient`, the main packages for `index.html` are not adjusted:
![image](https://user-images.githubusercontent.com/90312/187085487-0af6db2c-31db-4043-974b-eb0d67473ff5.png)

**Comment by rogerfar** [comment] 2023-03-09 03:36
I made some changes based on the official Angular recommendations. 

Can you try it in the new version and see if it works?

**Comment by goldenpipes** [comment] 2023-03-18 02:24
i cant seem to get it to work at all with rgegriffs conf.  i set the IP correctly, i should mention that my RDTclient is on a different machine than my nginx, but on the same local LAN. not sure that should matter, as other apps dont care where they are nginx proxies them just fine.  I have no idea how you set a baseurl or even if you do, i am also running this on unraid, maybe its my docker network thats the issue? thanks!

**Comment by rogerfar** [comment] 2023-03-19 15:35
@goldenpipes so it's fixed?

**Comment by sudoeste** [comment] 2023-06-09 17:48
@rogerfar unfortunatly it still doesn't work. Using an apache reverse proxy it tried to load everyting from / instead of folder/. 

Any chance the change sonarr and radarr implemented (changing root) is in the roadmap?

**Comment by rogerfar** [comment] 2023-06-11 16:59
I'm open for PR's because I have no idea what the issue is.

**Comment by sudoeste** [comment] 2023-06-11 17:12
I don't enough expertise to fix it myself but I can try and explain it a little better.

Imagine I want to host rdt-client in example.com/rdt/
For that I can use an apache / nginx reverse proxy to point the traffic of example.com/rdt/ to location_of_rdt-client:6500.

The only reason we can't do that is because while doing the above we manage to view the index.html in example.com/rdt/ rdt-client always referes the src / href / websocket included in the HTML without the base URL (as example.com/file.js instead of example.com/rdt/file.js) so all the css, images, JS files etc don't work.

Other tools like radarr / sonarr implemented the option to change the base url of the tool (in this case woult be location_of_rdt-client:6500/rdt/) and that enables us to use the tool behind a rproxy.

Yes, there are ways to rewrite / substitute the HTML / js passing through the proxy to alter the src / href to use /rdt/ instead of /

I hope I explained correctly

**Comment by rogerfar** [comment] 2023-06-11 17:14
If you check the browser console on page load it should show this:

![image](https://github.com/rogerfar/rdt-client/assets/1142915/74f9c401-3e53-4504-b5d4-28ab74d043e8)

What does this show for you?

**Comment by sudoeste** [comment] 2023-06-11 17:17
> 

Exactly the same. But using the rproxy means the base href to be changed to /rdt (or the folder we want to use).

The js files also have the same problem

**Comment by rogerfar** [comment] 2023-06-11 17:19
That's very odd, because there is some JS that runs and sets the base href on startup.

Can you run this piece of JS in your console: `window.location.pathname`? does it just return `/`?

**Comment by sudoeste** [comment] 2023-06-11 17:19
Forgot to include. If we use a subdomain (like it appears you are using) the problem doesn't exist! The problem only exists if we want the use a "folder" as the location of the proxy (I don't have a domain as my server is lan only)

**Comment by rogerfar** [comment] 2023-06-11 17:21
But what is your full domain? Is it something like `http://192.168.10.1/rdt`? or `http://server/rdt`?

**Comment by sudoeste** [comment] 2023-06-11 17:21
> That's very odd, because there is some JS that runs and sets the base href on startup.
> 
> Can you run this piece of JS in your console: `window.location.pathname`? does it just return `/`?

The problem is that if you use the rproxy to a folder the js won't ever run as the HTML tries to load it from example.com/file.js instead of example.com/rdt/file.js

**Comment by sudoeste** [comment] 2023-06-11 17:23
> But what is your full domain? Is it something like `http://192.168.10.1/rdt`? or `http://server/rdt`?

IT can be either of them. If the base URL of the tool is configurable both would work

**Comment by rogerfar** [comment] 2023-06-11 17:25
> > That's very odd, because there is some JS that runs and sets the base href on startup.
> > Can you run this piece of JS in your console: `window.location.pathname`? does it just return `/`?
> 
> The problem is that if you use the rproxy to a folder the js won't ever run as the HTML tries to load it from example.com/file.js instead of example.com/rdt/file.js

You can still run this if you simply put it in the console:
![image](https://github.com/rogerfar/rdt-client/assets/1142915/7e2be086-4a80-44ab-ba03-11bbe8981afe)

**Comment by sudoeste** [comment] 2023-06-11 17:32
> > > That's very odd, because there is some JS that runs and sets the base href on startup.
> > > Can you run this piece of JS in your console: `window.location.pathname`? does it just return `/`?
> > 
> > 
> > The problem is that if you use the rproxy to a folder the js won't ever run as the HTML tries to load it from example.com/file.js instead of example.com/rdt/file.js
> 
> You can still run this if you simply put it in the console: ![image](https://user-images.githubusercontent.com/1142915/244955092-7e2be086-4a80-44ab-ba03-11bbe8981afe.png)

Yes, the window.location.pathname is /

That makes the 4 js files being loaded from ip/files.js instead of ip/rdt/files.js

**Comment by rogerfar** [comment] 2023-06-11 17:38
But what is your full URL?

**Comment by sudoeste** [comment] 2023-06-11 17:39
Sorry, made a mistake.

![image](https://github.com/rogerfar/rdt-client/assets/3848104/3ea2b4c8-2ebe-427c-9e14-5daee36cc951)

**Comment by sudoeste** [comment] 2023-06-11 18:04
Made a few discoveries. Prefixing the index.html js paths ( src="rdt/runtime.52f1d05aa6c3afea.js") and changing all occurences of /Api to /rdt/Api inside main.js makes the rproxy to partially work

**Comment by rogerfar** [comment] 2023-06-11 18:31
I added an option to set the base href in the appsettings.json file in the next version, that should solve this issue.

**Comment by rogerfar** [comment] 2023-06-11 20:10
Try using 2.0.31, open `appsettings.json` and change the setting `BasePath` to `/rdt`.

**Comment by timcoop3r** [comment] 2023-06-13 13:52
@rogerfar might be worth moving this file to another path so us docker users can redirect the location to the docker host like we do with the DB? Or have the setting editable via the GUI?

Currently can only edit it by going into the running container. So any future upgrade of the container will remove the changes.

**Comment by sudoeste** [comment] 2023-06-13 14:00
> @rogerfar might be worth moving this file to another path so us docker users can redirect the location to the docker host like we do with the DB? Or have the setting editable via the GUI?
> 
> Currently can only edit it by going into the running container. So any future upgrade of the container will remove the changes.

Did you manage to make it work with docker? I still haven't managed

**Comment by sudoeste** [comment] 2023-06-13 18:04
> Try using 2.0.31, open `appsettings.json` and change the setting `BasePath` to `/rdt`.

Unfortunatly doesn't work. I did manage to make it to work in another way tho:

`<Location /rdt>
    ProxyPreserveHost on
    ProxyPass http://127.0.0.1:6500 connectiontimeout=10 timeout=300
    ProxyPassReverse http://127.0.0.1:6500

 AddOutputFilterByType SUBSTITUTE text/html
 Substitute "s|\"runtime|\"rdt/runtime|i"
 Substitute "s|\"polyfills|\"rdt/polyfills|i"
 Substitute "s|\"main|\"rdt/main|i"
 Substitute "s|href=\"styles|href=\"rdt/styles|i"

 AddOutputFilterByType SUBSTITUTE application/javascript

 Substitute "s|assets\/logo.png|rdt\/assets\/logo.png|i"
 Substitute "s|favicon.ico|rdt\/favico.ico|i"

 ProxyPass "ws://127.0.0.1:6500"

</Location>
`

**Comment by rogerfar** [comment] 2024-01-05 19:32
This should be good in the latest versions now.

**Closed by rogerfar** 2024-01-05 19:32 UTC

**Comment by adiberk** [comment] 2025-01-19 19:44
@rogerfar 
I set the env var in my docker container
BASE_PATH=/rdtclient

When I go to my network host though (localhost:6500/rdtclient) I am still unable to access the page.  Is there something else I need to do?

**Comment by adiberk** [comment] 2025-01-19 19:52
Seems to work now after going to regular login page.  Sorry - thanks again!
