### ISSUE TITLE
Many download errors??

### ISSUE THREAD

**Issue by Trusty555** [rogerfar/rdt-client#311] opened 2023-09-17 07:43 UTC
**What version are you using?**

**Wat OS are you running?**

**Are you using Docker or as a service?**

**Which debrid provider are you using?**

**Please attach a log file here with the log setting set to debug**

**Comment by Trusty555** [comment] 2023-09-17 07:51
![image](https://github.com/rogerfar/rdt-client/assets/77682548/30f41d41-e6e1-48ea-af57-46e99658c28f)
![image](https://github.com/rogerfar/rdt-client/assets/77682548/638656f3-0520-487b-b888-b8e1d6dca275)


Im using rogerfar/rdtclient docker on Unraid 6.12.4

Im gettting stuck on:
-Torrent finished, waiting for download links
-1/1 downloads failed with errors
-Torrent downloading (0% - 0 B/s) 

I do have some success, but many failures. Where to begin to fix this?

**Comment by Trusty555** [comment] 2023-09-17 11:37
![image](https://github.com/rogerfar/rdt-client/assets/77682548/9f1a8e97-3fa7-43be-a174-401b7e914944)

**Comment by BlueBull010** [comment] 2023-09-17 11:49
I have the same problem, but in my case it's every download. It starts to download without a problem but when it gets to the end of the download, somewhere between 75% downloaded and 99%, it fails with that same SSL error as you have. In my case not a single download succeeds

**Comment by Trusty555** [comment] 2023-09-17 11:53
> I have the same problem, but in my case it's every download. It starts to download without a problem but when it gets to the end of the download, somewhere between 75% downloaded and 99%, it fails with that same SSL error as you have. In my case not a single download succeeds

Yes that's what mine are doing getting to 100% and then show 'error'

Have you ever had success?

**Comment by BlueBull010** [comment] 2023-09-17 11:57
> > I have the same problem, but in my case it's every download. It starts to download without a problem but when it gets to the end of the download, somewhere between 75% downloaded and 99%, it fails with that same SSL error as you have. In my case not a single download succeeds
> 
> Yes that's what mine are doing getting to 100% and then show 'error'
> 
> Have you ever had success?

Yes, up until about a month ago it worked quite flawlessly. Then I had an issue but that was apparently because of folder permissions I found out. So I don't know how long this SSL error has been happening because I had another error before it got to that point. I fixed that permission error a few days ago and have been having these SSL errors ever since. But before all that, this download client worked perfectly and I've been using it for years, it's great

My error message:
`2023-09-17 13:46:38.285 +02:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: The SSL connection could not be established, see inner exception. for download <DOWNLOAD FILENAME> Completed: -2147483648%, avg speed: 0bytes/s (8b1292e1-4dd7-466f-9fad-5b83e2ed906d) for torrent <TORRENT NAME> (2BDVFC7WOC56C - downloaded 100%) (36cb537b-5b44-4a45-8801-7e7b5d7038a5)`

**Comment by Trusty555** [comment] 2023-09-17 12:06
> > > I have the same problem, but in my case it's every download. It starts to download without a problem but when it gets to the end of the download, somewhere between 75% downloaded and 99%, it fails with that same SSL error as you have. In my case not a single download succeeds
> > 
> > 
> > Yes that's what mine are doing getting to 100% and then show 'error'
> > Have you ever had success?
> 
> Yes, up until about a month ago it worked quite flawlessly. Then I had an issue but that was apparently because of folder permissions I found out. So I don't know how long this SSL error has been happening because I had another error before it got to the downloading stage. I fixed that permission error a few days ago and have been having these SSL errors ever since. But before all that, this download client worked perfectly and I've been using it for a few years already. It's fantastic, I can't go without it anymore
> 
> My error message: `2023-09-17 13:46:38.285 +02:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: The SSL connection could not be established, see inner exception. for download <DOWNLOAD FILENAME> Completed: -2147483648%, avg speed: 0bytes/s (8b1292e1-4dd7-466f-9fad-5b83e2ed906d) for torrent <TORRENT NAME> (2BDVFC7WOC56C - downloaded 100%) (36cb537b-5b44-4a45-8801-7e7b5d7038a5)`

ah so its not just me then, as this my first time setting it up and seems very inconsistent so far. What OS are you running? Im on Unraid

I also tried Deluge as an alternative, but that was incredibly slow, like 5kb/s

So at this moment the best solution is just to DL packs directly from Kodi. At least its reliable and fast.

The concept of Radarr/Sonarr seems great, but if you can't download its not very useful

**Comment by BlueBull010** [comment] 2023-09-17 12:15
> > > > I have the same problem, but in my case it's every download. It starts to download without a problem but when it gets to the end of the download, somewhere between 75% downloaded and 99%, it fails with that same SSL error as you have. In my case not a single download succeeds
> > > 
> > > 
> > > Yes that's what mine are doing getting to 100% and then show 'error'
> > > Have you ever had success?
> > 
> > 
> > Yes, up until about a month ago it worked quite flawlessly. Then I had an issue but that was apparently because of folder permissions I found out. So I don't know how long this SSL error has been happening because I had another error before it got to the downloading stage. I fixed that permission error a few days ago and have been having these SSL errors ever since. But before all that, this download client worked perfectly and I've been using it for a few years already. It's fantastic, I can't go without it anymore
> > My error message: `2023-09-17 13:46:38.285 +02:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: The SSL connection could not be established, see inner exception. for download <DOWNLOAD FILENAME> Completed: -2147483648%, avg speed: 0bytes/s (8b1292e1-4dd7-466f-9fad-5b83e2ed906d) for torrent <TORRENT NAME> (2BDVFC7WOC56C - downloaded 100%) (36cb537b-5b44-4a45-8801-7e7b5d7038a5)`
> 
> ah so its not just me then, as this my first time setting it up and seems very inconsistent so far. What OS are you running? Im on Unraid
> 
> I also tried Deluge as an alternative, but that was incredibly slow, like 5kb/s
> 
> So at this moment the best solution is just to DL packs directly from Kodi. At least its reliable and fast.
> 
> The concept of Radarr/Sonarr seems great, but if you can't download its not very useful

I'm on a Windows VM running on vSphere. But I do have two Unraid servers as well and have been considering moving it to a container on one of them for a while. Might take a look at that soon. But torrents for me are a secondary download system, a backup. My main one is usenet. It has almost everything and it always downloads at full speed, if you have a good provider. My usenet downloads are always as fast as my connection can go, about 120MB/s. Torrents are only used for stuff that isn't found on usenet or isn't found in the qualities I want, then my system looks for a torrent automatically. 

Sonarr and Radarr are great indeed. Also look into Prowlarr, which is a torrent and usenet search engine that handles all your usenet indexers and torrent trackers and it takes care of the search queries coming from Sonarr/Radarr. It is a fantastic addition to a Sonarr/Radarr setup. Then you also have Lidarr for music, Readarr for eBooks, Bazarr to download your subtitles automatically and Overseerr to let your users request media to download. I have all of them running, along with some other services

**Comment by Trusty555** [comment] 2023-09-17 12:29
> which is a torrent and usenet search engine that handles all your usenet indexers and torrent trackers and it takes care of the search queries coming from Sonarr/Radarr. It is a fantastic addition to a Sonarr/Radarr setup. Then you also have Lidarr for music, Readarr for eBooks, Bazarr to download your subtitles automatically and Overseerr to let your users request media to download and to discover new media. I have all of them running, along with a bunch of other services

Well yeah the concept of real debrid is a similar idea as usenet (from your description) in terms of high speed, high quality, has everything and their cached files. That's the whole reason I'm trying to get rdt-client to work.

So now I'm confused why would you use RD if you have usenet? Unless of course for streaming on Kodi

If I go the usenet route, could you please recommend the best options, from what I've seen so far is NZBGet or SABnzbd, and what indexer would you suggest?

**Comment by BlueBull010** [comment] 2023-09-17 12:43
> > which is a torrent and usenet search engine that handles all your usenet indexers and torrent trackers and it takes care of the search queries coming from Sonarr/Radarr. It is a fantastic addition to a Sonarr/Radarr setup. Then you also have Lidarr for music, Readarr for eBooks, Bazarr to download your subtitles automatically and Overseerr to let your users request media to download and to discover new media. I have all of them running, along with a bunch of other services
> 
> Well yeah the concept of real debrid is a similar idea as usenet (from your description) in terms of high speed, high quality, has everything and their cached files. That's the whole reason I'm trying to get rdt-client to work.
> 
> So now I'm confused why would you use RD if you have usenet? Unless of course for streaming on Kodi
> 
> If I go the usenet route, could you please recommend the best options, from what I've seen so far is NZBGet or SABnzbd, and what indexer would you suggest?

Because in rare cases there are things that, for whatever reason, aren't found on usenet. It's free, so no reason not to set it up, always good to have a backup. And no, I don't use Kodi, my media is stored on my Unraid servers, I like having offline access to my media and I'm a bit of a data hoarder as well, lol

NZBget isn't maintained anymore, so I would go for SabNZB. I find NZBget to be a bit better though, personally, so if you don't mind using unmaintained software you could also use that. Both are great. As for indexers, the more the better, since they are very cheap and different indexers have different media indexed. Below you can find mine, screenshot taken from Prowlarr. You do need an invite for most of them though, although one of the best ones, NZBGeek, has open registration I believe. I would start with that one. The last image are statistics on my indexers, so you have an idea which indexer has given me the most succesful downloads
![image](https://github.com/rogerfar/rdt-client/assets/61655638/8b7e5b6e-7877-4339-84b3-9b1d8256a134)
![image](https://github.com/rogerfar/rdt-client/assets/61655638/a78f81a9-e32d-40c2-97c5-f22b31d1f769)

**Comment by Trusty555** [comment] 2023-09-17 13:00
> > > which is a torrent and usenet search engine that handles all your usenet indexers and torrent trackers and it takes care of the search queries coming from Sonarr/Radarr. It is a fantastic addition to a Sonarr/Radarr setup. Then you also have Lidarr for music, Readarr for eBooks, Bazarr to download your subtitles automatically and Overseerr to let your users request media to download and to discover new media. I have all of them running, along with a bunch of other services
> > 
> > 
> > Well yeah the concept of real debrid is a similar idea as usenet (from your description) in terms of high speed, high quality, has everything and their cached files. That's the whole reason I'm trying to get rdt-client to work.
> > So now I'm confused why would you use RD if you have usenet? Unless of course for streaming on Kodi
> > If I go the usenet route, could you please recommend the best options, from what I've seen so far is NZBGet or SABnzbd, and what indexer would you suggest?
> 
> Because in rare cases there are things that, for whatever reason, aren't found on usenet. It's free, so no reason not to set it up, always good to have a backup. And no, I don't use Kodi, my media is stored on my Unraid servers, I like having offline access to my media and I'm a bit of a data hoarder as well, lol
> 
> NZBget isn't maintained anymore, so I would go for SabNZB. I find NZBget to be a bit better though, personally, so if you don't mind using unmaintained software you could also use that. Both are great. My usenet provider is Eweka, but I have a few others as a backup as well. Eweka is located near to where I live so they give me fantastic speeds. As for indexers, the more the better, since they are very cheap and different indexers have different media indexed. Below you can find mine, screenshot taken from Prowlarr. You do need an invite for most of them though, although one of the best ones, NZBGeek, has open registration I believe. I would start with that one. The last image are statistics on my indexers, so you have an idea which indexer has given me the most succesful downloads. These are the statistics of the last 90 days ![image](https://user-images.githubusercontent.com/61655638/268502681-466a2faf-b945-42cf-ba8e-d389a474684d.png) ![image](https://user-images.githubusercontent.com/61655638/268502374-a78f81a9-e32d-40c2-97c5-f22b31d1f769.png)
> 
> By the way, we better remove this conversation, it's a bit too off-topic in this Github-repository, lol. Let me know when you've read it, so I can delete my messages. I'll delete my messages in half an hour at the latest

thanks for the help, yeah we can delete

**Comment by BlueBull010** [comment] 2023-09-20 11:52
> > > > I have the same problem, but in my case it's every download. It starts to download without a problem but when it gets to the end of the download, somewhere between 75% downloaded and 99%, it fails with that same SSL error as you have. In my case not a single download succeeds
> > > 
> > > 
> > > Yes that's what mine are doing getting to 100% and then show 'error'
> > > Have you ever had success?
> > 
> > 
> > Yes, up until about a month ago it worked quite flawlessly. Then I had an issue but that was apparently because of folder permissions I found out. So I don't know how long this SSL error has been happening because I had another error before it got to the downloading stage. I fixed that permission error a few days ago and have been having these SSL errors ever since. But before all that, this download client worked perfectly and I've been using it for a few years already. It's fantastic, I can't go without it anymore
> > My error message: `2023-09-17 13:46:38.285 +02:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: The SSL connection could not be established, see inner exception. for download <DOWNLOAD FILENAME> Completed: -2147483648%, avg speed: 0bytes/s (8b1292e1-4dd7-466f-9fad-5b83e2ed906d) for torrent <TORRENT NAME> (2BDVFC7WOC56C - downloaded 100%) (36cb537b-5b44-4a45-8801-7e7b5d7038a5)`
> 
> ah so its not just me then, as this my first time setting it up and seems very inconsistent so far. What OS are you running? Im on Unraid
> 
> I also tried Deluge as an alternative, but that was incredibly slow, like 5kb/s
> 
> So at this moment the best solution is just to DL packs directly from Kodi. At least its reliable and fast.
> 
> The concept of Radarr/Sonarr seems great, but if you can't download its not very useful

Update: Because I was curious I ran the downloader in a docker container on one of my unraid arrays. This time I did not get SSL errors and the downloads complete successfully. At first I thought it was because of my VPN, since my windows box downloads through VPN but my unraid array does not. However, disabling my VPN didn't solve it and also downloading from real-debrid through another download client (JDownloader) on my windows box also doesn't produce SSL errors, neither with nor without VPN. So I still have no idea what the problem is, but it doesn't occur on my unraid docker for some reason

**Comment by Trusty555** [comment] 2023-09-22 09:48
> > > > > I have the same problem, but in my case it's every download. It starts to download without a problem but when it gets to the end of the download, somewhere between 75% downloaded and 99%, it fails with that same SSL error as you have. In my case not a single download succeeds
> > > > 
> > > > 
> > > > Yes that's what mine are doing getting to 100% and then show 'error'
> > > > Have you ever had success?
> > > 
> > > 
> > > Yes, up until about a month ago it worked quite flawlessly. Then I had an issue but that was apparently because of folder permissions I found out. So I don't know how long this SSL error has been happening because I had another error before it got to the downloading stage. I fixed that permission error a few days ago and have been having these SSL errors ever since. But before all that, this download client worked perfectly and I've been using it for a few years already. It's fantastic, I can't go without it anymore
> > > My error message: `2023-09-17 13:46:38.285 +02:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: The SSL connection could not be established, see inner exception. for download <DOWNLOAD FILENAME> Completed: -2147483648%, avg speed: 0bytes/s (8b1292e1-4dd7-466f-9fad-5b83e2ed906d) for torrent <TORRENT NAME> (2BDVFC7WOC56C - downloaded 100%) (36cb537b-5b44-4a45-8801-7e7b5d7038a5)`
> > 
> > 
> > ah so its not just me then, as this my first time setting it up and seems very inconsistent so far. What OS are you running? Im on Unraid
> > I also tried Deluge as an alternative, but that was incredibly slow, like 5kb/s
> > So at this moment the best solution is just to DL packs directly from Kodi. At least its reliable and fast.
> > The concept of Radarr/Sonarr seems great, but if you can't download its not very useful
> 
> Update: Because I was curious I ran the downloader in a docker container on one of my unraid arrays. This time I did not get SSL errors and the downloads complete successfully. At first I thought it was because of my VPN, since my windows box downloads through VPN but my unraid array does not. However, disabling my VPN didn't solve it and also downloading from real-debrid through another download client (JDownloader) on my windows box also doesn't produce SSL errors, neither with nor without VPN. So I still have no idea what the problem is, but it doesn't occur on my unraid docker for some reason

ah after speaking with you I now have SABnzbd with news.newshosting.com and NZBgeek indexer set up, got Radarr / Sonnar file system all sorted and now everything is working like a dream. I also followed TRaSH guides for quality profiles / Release Profiles / custom formats which enabled me to re-download everything I had in the best possible format / quality.

Just today I came across my first hurdle with TV show 'Six Feet Under', with NZB I could only get S05, the rest show 'missing article' I added another block server (blocknews.net) but that didn't help, I assume its DMCA'd. So I looked it up on Kodi (Fen) via RD and its all being DL'd from there. I just DL directly from KODI as I can find download packs (full seasons), later I'll manual import into Sonnar

**Comment by BlueBull010** [comment] 2023-09-22 10:46
Wow, you've been busy, that is impressively fast to set up such an entire system. Check your notifications on Github ;-)

**Comment by Trusty555** [comment] 2023-09-22 11:29
> Wow, you've been busy, that is impressively fast to set up such an entire system. Check your notifications on Github, you should see one from my repository ;-)

no notifications bro

**Comment by BlueBull010** [comment] 2023-09-22 11:30
> > Wow, you've been busy, that is impressively fast to set up such an entire system. Check your notifications on Github, you should see one from my repository ;-)
> 
> no notifications bro

https://github.com/BlueBull010/unraid-tartubedocker-private/issues/1

**Comment by rogerfar** [comment] 2024-01-05 19:22
Try again with the latest version, new downloader should fix this.

**Closed by rogerfar** 2024-01-05 19:22 UTC
