### ISSUE TITLE
Add a post-download trigger

### ISSUE THREAD

**Issue by profucius** [rogerfar/rdt-client#95] opened 2021-11-28 19:09 UTC
I am developing a workaround for adding torrents externally, when RDT detects this and downloads the files, I'm trying to have a post process kick in after the files finish downloading. Normally if those torrents are added by Sonarr or Radarr, they will handle their own post-download processes, but for anything added externally it requires manually checking.

I propose a feature added that when an externally-added torrent is completed downloading locally, a user-created event occurs. For instance, running a .BAT file locally, or at the very least, adding an entry into a log file that I can sniff using a separate textfile-has-changed macro application.

This would allow me to build out my own post-download macro for handling files that are externally added/downloaded.

**Comment by rogerfar** [comment] 2022-03-19 23:15
Duplicate of #106, but this has now been added.

**Closed by rogerfar** 2022-03-19 23:15 UTC
