### ISSUE TITLE
Stuck on Queued for Unpacking

### ISSUE THREAD

**Issue by MVethana** [rogerfar/rdt-client#82] opened 2021-10-06 23:13 UTC
v1.8.4
W10 64
Running as Service

Certain torrents get stuck on the Queued for unpacking status with these errors

` An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at RdtClient.Data.Data.TorrentData.UpdateComplete(Guid torrentId, Nullable`1 datetime) in C:\Projects\rdt-client\server\RdtClient.Data\Data\TorrentData.cs:line 169
   at RdtClient.Service.Services.Torrents.Delete(Guid torrentId, Boolean deleteData, Boolean deleteRdTorrent, Boolean deleteLocalFiles) in C:\Projects\rdt-client\server\RdtClient.Service\Services\Torrents.cs:line 217
   at RdtClient.Service.Services.Torrents.RetryTorrent(Guid torrentId) in C:\Projects\rdt-client\server\RdtClient.Service\Services\Torrents.cs:line 406
   at RdtClient.Web.Controllers.TorrentsController.Retry(Guid torrentId) in C:\Projects\rdt-client\server\RdtClient.Web\Controllers\TorrentsController.cs:line 161
   at lambda_method1114(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Web.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in C:\Projects\rdt-client\server\RdtClient.Web\Startup.cs:line 113
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in C:\Projects\rdt-client\server\RdtClient.Service\Middleware\AuthorizeMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
[19:05:05 ERR] Unexpected error occurred in TorrentDownloadManager.Tick
System.NullReferenceException: Object reference not set to an instance of an object.
   at RdtClient.Service.Services.UnpackClient.Start() in C:\Projects\rdt-client\server\RdtClient.Service\Services\UnpackClient.cs:line 65
   at RdtClient.Service.Services.TorrentRunner.Tick() in C:\Projects\rdt-client\server\RdtClient.Service\Services\TorrentRunner.cs:line 338
   at RdtClient.Service.Services.TaskRunner.ExecuteAsync(CancellationToken stoppingToken) in C:\Projects\rdt-client\server\RdtClient.Service\Services\TaskRunner.cs:line 38`

From what I can tell specific torrents have problems while others download without issue

**Comment by MVethana** [comment] 2021-10-07 14:45
New issue now, Value cannot be null for "path2"

https://pastebin.com/jrci6UYE

**Comment by MVethana** [comment] 2021-10-07 18:40
Also getting resource not found errors now

`
[14:26:56 ERR] Unexpected error occurred in TorrentDownloadManager.Tick
RDNET.Exceptions.RealDebridException: Resource not found
   at RDNET.Apis.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Apis.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Apis.Requests.GetRequestAsync[T](String url, Boolean requireAuthentication, CancellationToken cancellationToken)
   at RDNET.Apis.TorrentsApi.GetInfoAsync(String id, CancellationToken cancellationToken)
   at RdtClient.Service.Services.Torrents.Update(Torrent torrent) in C:\Projects\rdt-client\server\RdtClient.Service\Services\Torrents.cs:line 637
   at RdtClient.Service.Services.Torrents.Update() in C:\Projects\rdt-client\server\RdtClient.Service\Services\Torrents.cs:line 365
   at RdtClient.Service.Services.TorrentRunner.Tick() in C:\Projects\rdt-client\server\RdtClient.Service\Services\TorrentRunner.cs:line 179
   at RdtClient.Service.Services.TaskRunner.ExecuteAsync(CancellationToken stoppingToken) in C:\Projects\rdt-client\server\RdtClient.Service\Services\TaskRunner.cs:line 38
`

**Comment by MVethana** [comment] 2021-10-08 22:10
I was able to narrow down the download->unpack->download as normal behavior when rdt encounters a pack of files which are not compressed as it does that for each file in the pack

It is probably a good idea to change the ui to signify the current status of which item in the pack is being downloaded/unpacked.

The issue however of it getting seemingly getting stuck for no reason is the main issue right now. It seems to randomally get stuck and the entire time prior it outputs the Object Reference not set to an instance of an object error.

**Comment by MVethana** [comment] 2021-10-19 04:24
Seen it happen multiple times, next time i see it will send a pastebin link, also just noticed not sure if it started this update but under tests the download path perms and write speed test work fine, however the download test errors out with the file being used by another process. @rogerfar could this have something to do with it?

**Comment by MVethana** [comment] 2021-10-20 16:01
Got another if you need more data

![image](https://user-images.githubusercontent.com/17278251/138128889-ff7daef2-313e-48ff-8c96-532fb4aa35fb.png)
![image](https://user-images.githubusercontent.com/17278251/138128921-cbee37fe-ce0c-4f3b-87dd-9e481d72e730.png)
https://pastebin.com/w5Qw1ke0

**Comment by MVethana** [comment] 2021-10-20 20:09
So in that case its something specific about the torrent causing it if both of us can replicate it. Are you able to test if you used sonarr and qbit directly instead of using rdt does it still occur?

**Comment by rogerfar** [comment] 2021-10-20 22:53
I think I figured it out. Some of the torrents that have been downloaded before to Real Debrid have not been fully downloaded. For example the first torrent has 10 episodes, BUT for some reason somebody decided to only download the first 9.

Sonarr expects 10 episodes, but only receives 9, so it goes a bit wonky. I reported this as a bug to Sonarr, but they have already closed it as expected behaviour.

To circumvent this, make sure you DON'T have this checkbox checked:
![image](https://user-images.githubusercontent.com/1142915/138183251-01b8e9b8-f568-4b21-8a54-64860f3bdd68.png)

This checkbox generally works well for single episode torrents, but not for multi file torrents.

If you want more logs, you can change the `appsettings.json` file and restart the service. If you have a large amount of downloads I suggest using Aria2 first as it better supports download interruptions.

**Comment by MVethana** [comment] 2021-10-20 23:23
Switching to Aria2 to see if that fixes the other issues im having and i unchecked that checkbox. If I notice anything else will post and update with any logs I get

**Comment by MVethana** [comment] 2021-10-24 00:42
I am honestly really surprised. It looks like that actually fixed it. Did think it could be that simple. Sonarr imported all the files this time. Only thing is that Aria2 is done with the downloads and sonarr has imported them. However rdt says they are still downloading.
![image](https://user-images.githubusercontent.com/17278251/138575482-a717ef87-fcd5-4118-bc61-e6fa09c3f4fa.png)
![image](https://user-images.githubusercontent.com/17278251/138575498-854649de-7c05-4e6b-9ebc-6a965b24a45f.png)

Even though rdt thinks they are still downloading, sonarr has already imported the files but the files still exist in the rdt folder so there are 2 copies of them right now. If anything RDT looks to be in some kind of glitched state because there is no disk or network activity at all. I'm attaching the logs, lmk if you need anything else

[rdtclient.log](https://github.com/rogerfar/rdt-client/files/7403876/rdtclient.log)
[rdtclient_001.log](https://github.com/rogerfar/rdt-client/files/7403877/rdtclient_001.log)
[rdtclient_002.log](https://github.com/rogerfar/rdt-client/files/7403883/rdtclient_002.log)
[aria2.txt](https://github.com/rogerfar/rdt-client/files/7403885/aria2.txt)

**Comment by MVethana** [comment] 2021-10-30 04:51
Ran into the same internal error, RDNET.Exceptions.RealDebridException: Internal error again, any idea when the update will be pushed or what I can do to mitigate the issue on my end until then? Is there a dev branch you're using we can use to test the changes you are making?

**Comment by rogerfar** [comment] 2021-10-30 18:34
Those changes weren't ready yet, I have pushed 1.9.6 with those changes.

**Comment by MVethana** [comment] 2021-11-01 21:45
Tried 1.9.6 for 2 days, found some more issues will post them here as I reproduce and get logs,

First one is a season pack torrent, the torrent should have multiple files and RD recognizes this when trying to add the torrent manually.
![image](https://user-images.githubusercontent.com/17278251/139745871-4c3cb3a4-0ee4-4cae-be72-404cd05a4ecd.png)

However for whatever reason RD only reports one file which RDT and Aria download fine but then sonarr complains files are missing because RD didn't have all the files it was supposed to. In this case the torrent should be marked as failed so that Sonarr can look for a different torrent.

[rdtclient.log](https://github.com/rogerfar/rdt-client/files/7456302/rdtclient.log)
[aria2.txt](https://github.com/rogerfar/rdt-client/files/7456304/aria2.txt)

[sonarr.debug.1.txt](https://github.com/rogerfar/rdt-client/files/7456312/sonarr.debug.1.txt)
[sonarr.debug.2.txt](https://github.com/rogerfar/rdt-client/files/7456313/sonarr.debug.2.txt)
[sonarr.debug.3.txt](https://github.com/rogerfar/rdt-client/files/7456314/sonarr.debug.3.txt)
[sonarr.debug.txt](https://github.com/rogerfar/rdt-client/files/7456315/sonarr.debug.txt)
[sonarr.txt](https://github.com/rogerfar/rdt-client/files/7456316/sonarr.txt)
[sonarr.0.txt](https://github.com/rogerfar/rdt-client/files/7456317/sonarr.0.txt)
[sonarr.1.txt](https://github.com/rogerfar/rdt-client/files/7456318/sonarr.1.txt)
[sonarr.2.txt](https://github.com/rogerfar/rdt-client/files/7456319/sonarr.2.txt)
[sonarr.debug.0.txt](https://github.com/rogerfar/rdt-client/files/7456320/sonarr.debug.0.txt)

**Comment by MVethana** [comment] 2021-11-01 22:27
Second issue is that if one file in a torrent with multiple files fails due to RD error/etc., rdt does some undesirable things

- From what I can see rdt attempts to retry the entire torrent and redownloads all the files which is a waste especially when all the other files in the torrent was successful. RDT should instead retry the torrent with only the problematic file selected to prevent wasting bandwidth and disk writes.
- As the example in this case, RDT finishes with the status "1/13 downloads failed with errors". It seems that there is an issue where RDT gets stuck and hangs after this but I could be wrong. I didn't see any disk or network activity. However, if this is the final result, RDT should pass the successful files to sonarr/etc. and mark the downloadable file as failed or in the case of it being a temporary RDT error, pass the successful files on right away and attempt to download the problem file later depending on user preference, possibly a user definable setting. This is more optimal to failing the entire torrent just because 1 file was problematic

[aria2.txt](https://github.com/rogerfar/rdt-client/files/7456461/aria2.txt)
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/7456462/rdtclient.log)

[sonarr.debug.1.txt](https://github.com/rogerfar/rdt-client/files/7456456/sonarr.debug.1.txt)
[sonarr.debug.txt](https://github.com/rogerfar/rdt-client/files/7456457/sonarr.debug.txt)
[sonarr.txt](https://github.com/rogerfar/rdt-client/files/7456458/sonarr.txt)
[sonarr.debug.0.txt](https://github.com/rogerfar/rdt-client/files/7456459/sonarr.debug.0.txt)

**Comment by MVethana** [comment] 2021-11-02 04:39
Third issue, it seems like invalid torrents are still getting stuck, as an example if you try the magnet link I sent you earlier, RDT retries it once and it hangs there, preferably it would get automatically removed and marked as failed to sonarr/etc. so that a new torrent can be found

**Comment by rogerfar** [comment] 2021-11-02 14:50
The clonewars looks like a timing issue. RealDebrid sometimes gives 1 RAR and sometimes lots of files, I don't know where the cutoff is exactly. The issue is that the torrent reports are completed, BUT it's still doing something in the background and it takes a while for the download links to be available. So it is possible that it checks and there is only 1 file available, even though more are expected. So I guess for now I will add in a delay of 1 minute as a precaution. This shouldn't affect the 90% of torrents which don't get rarred up.

**Comment by MVethana** [comment] 2021-11-02 15:32
Spent some more time testing and I don't think this is the issue. When downloading the whole torrent with all the files using the RD gui on the website, it returns the same 1 file on server 28. I don't think its a timing issue because this happens every single time using the native gui. However, modifying which files are selected by removing the featurettes or even a single featurette file results in RD attempting to redownload the torrent again to a different server which has all the files that are expected in that instance.

To me it seems like somehow when it cached that torrent with every file selected, only the first episode got cached and RD will always return that when asking for all files due to this bug.

How were you able to get lots of files from this torrent? Did you modify which files you asked for? I decided to add the torrent to the website last night with every file selected and right now it still only displays 1 file when on server 28 so I am inclined to say it is not a timing issue.

**Comment by rogerfar** [comment] 2021-11-02 22:07
I see yes, it looks like that torrent is just completely broken, I'm not sure what we can do about that.

Even removing the torrent and re-adding it doesn't fix it.

**Comment by MVethana** [comment] 2021-11-02 22:11
Since I feel like this has something to do with RD and not that torrent itself since the issue seems to be related to what files RD decided to cache, possibly just do a check to ensure that all the expected files were received and if not just mark it as failed so that sonarr/etc. can look for a new one

**Comment by MVethana** [comment] 2021-11-02 22:51
Another issue I found, if RDT is unpacking but the torrent is removed/deleted mid unpack, the torrent isn't shown in the torrents section anymore of RDT but the unpack process continues. Upon deletion, any in progress unpacking processes should be cancelled and the files should be deleted

**Comment by MVethana** [comment] 2021-11-03 01:06
I ended up finding another torrent that has the exact same server. Funnily enough its on the exact same server that had an issue with the clone wars torrent, server 28, possibly a more widespread issue affecting that server that might need to be reported to RD possibly?

**Comment by rogerfar** [comment] 2021-11-21 18:41
@MVethana I'm going to close this issue as we've solved multiple issues in here now, and I must thank you for your dedication to testing, a lot of issues came to light without doing some heavy stress testing! Unfortunately Real-Debrid itself doesn't make it easy sometimes, but if you still have specific issues, please open a new ticket and I'll have a look at it again.

**Closed by rogerfar** 2021-11-21 18:41 UTC
