### ISSUE TITLE
Download of sub-folders with premiumize.me not working

### ISSUE THREAD

**Issue by kungfoolfighting** [rogerfar/rdt-client#281] opened 2023-07-17 07:58 UTC
**What version are you using?**
v.2.0.32

**Wat OS are you running?**
Linux
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug**
Don't have the relevant logs in question anymore.
But should be very easy to reproduce.

I have had this with multiple torrents:
If there is a file in the root directory of the torrent download directory on premiumize.me and other sub-folders as well, then rdt-client will download the single file in the root directory and in the web UI claim that the torrent download has finished even though it didn't download the sub folders.

**Comment by kungfoolfighting** [comment] 2023-07-18 16:55
I have locally coded a fix for this. Will create a pull request tomorrow.

**Comment by rogerfar** [comment] 2023-08-11 20:04
Could you provide a test torrent I can test with?

**Comment by rogerfar** [comment] 2023-09-02 21:55
Duplicate of #294 and fixed in the next version.

**Closed by rogerfar** 2023-09-02 21:55 UTC

**Comment by kungfoolfighting** [comment] 2023-09-19 09:09
I looked at the code of your fix for this issue. 
The new implementation will flatten the folder hierarchy. 
If you download a music album with 2 CDs where the individual CDs are in the CD1 and CD2 subfolder, you will now download everything to the root folder of the download and the tracks of both CDs will be interleaved.
The PR that I opened adds target download folders to the downloads to solve this issue. This of course makes the code a little more complicated, but I think this change is necessary. Other than that, your fix is similar to mine, but adds a lot more debugging logs, that I don't have.
Could you add this functionality as well? Currently this is preventing me from updating to your upstream version from my fork, because I think this is necessary to fix.
