### ISSUE TITLE
Categories and destination folders

### ISSUE THREAD

**Issue by kxzaon** [rogerfar/rdt-client#135] opened 2022-04-18 23:17 UTC
**What version are you using?**

Version 2.0.12

**Wat OS are you running?**

Ubuntu 18.10

**Are you using Docker or as a service?**

Docker

Your client is working very well since several months on my setup with radarr, but I added another instance of radarr recently to download only 4k movies. And instead of importing only from the right category, radarr instances are trying to import whatever the category is and the destination folder is. 
To be clear, my radarrSD instance imports my rdtclient downloads sent by radarr4k. The category are different and the download folder as well.
My other download clients are working perfectly well (nzbget for instance) with radarr instances and the category specified as parameter. 
Am i the only one with this big issue ?
Thanks for your help.

**Comment by ozdek** [comment] 2022-04-30 11:48
I have the same issue. Not everyone has 2 sonarr instances I believe :) I have 2 radarr as well. So a bit problematic.

**Comment by rogerfar** [comment] 2022-04-30 15:13
I'm not entirely sure what the issue is. I have multiple instances running too but they don't cross contaminate eachother, as far as I know Sonarr keeps track of what it added to the downloader and ignores the rest.

What do you have your Sonarr and Radarr categories set to?

**Comment by ozdek** [comment] 2022-04-30 15:24
> 

Mines are easy:
sonarr
sonarr4k
radarr
radarr4k

The problem is categories are not shown or respected(?) in sonarr or radarr. That means sonarr can see them both at the same time and import sonarr4k downloads by mistake if the same show is in that database (it usually is because 1080p library already covers 4k library)

Because of this I can only use sonarr and radarr at the moment.

**Comment by rogerfar** [comment] 2022-04-30 15:28
Can you show a screenshot of the settings of all 4 instances?

**Comment by ozdek** [comment] 2022-04-30 15:30
> Can you show a screenshot of the settings of all 4 instances?

![image](https://user-images.githubusercontent.com/65017832/166112002-5f1e8ab9-c366-420b-978c-965710dad2d5.png)
Like this?

**Comment by rogerfar** [comment] 2022-04-30 15:30
Yes

**Comment by ozdek** [comment] 2022-04-30 15:31
> Yes

![image](https://user-images.githubusercontent.com/65017832/166112074-ee04d794-8176-4254-b3f8-aeeb580c3684.png)
I can only do it one by one for some reason. Bear with me :)

**Comment by ozdek** [comment] 2022-04-30 15:33
![image](https://user-images.githubusercontent.com/65017832/166112161-17fc0f73-3bd2-429e-bfb2-a254f4596778.png)

**Comment by ozdek** [comment] 2022-04-30 15:34
![image](https://user-images.githubusercontent.com/65017832/166112187-5d40c1c3-e773-4f47-b2ad-9f33b364cbe0.png)
Done.

**Comment by ozdek** [comment] 2022-04-30 15:56
I have tried it again with these settings. 4k download is being imported into 1080p library at the moment.

Radarr deleted 1080p copy thinking it is importing that.
Radarr4k imported the 4k copy. Sometimes it is the other way around because there is only one download. Which one imports it faster is the key :)

**Comment by rogerfar** [comment] 2022-05-14 17:58
This should now be resolved in the latest version as it properly queries the API for torrents in a specific category.

**Closed by rogerfar** 2022-05-14 17:58 UTC
