### ISSUE TITLE
Slow Download Speed when using NFS as docker volume.

### ISSUE THREAD

**Issue by AlbanVidalenche** [rogerfar/rdt-client#11] opened 2020-12-20 00:57 UTC
I've been trying to use rdt-client as a docker container.

My NFS setup gives me around 80 to 90 mo/s with other download clients, and when I try with rdt-client, i can't get more than 500 KB/s.
I finally tried with a local docker volume, and i get normal speeds, so the issue seems to be related to the NFS.

Thank you for the work on this project, it's very helpful.

**Comment by rogerfar** [comment] 2020-12-20 00:58
Did you use the docker container or windows service?

**Comment by AlbanVidalenche** [comment] 2020-12-20 01:03
I use the docker container

**Comment by AlbanVidalenche** [comment] 2020-12-20 01:10
Here is my docker-compose file 

` 
services
 rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    volumes:
      - downloads:/data/downloads
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
        - 5003:6500
    restart: unless-stopped

volumes
  downloads:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=X.X.X.X,nolock,soft,rw"
      device: ":/path/downloads"
`

**Comment by rogerfar** [comment] 2020-12-20 01:31
Thanks for sharing that, what host os is that on?

I made the docker container last week but haven't put it through testing yet. I have some time off next few weeks so I can spend some time on it.

**Comment by AlbanVidalenche** [comment] 2020-12-20 10:30
I'm using Ubuntu 20.04, with NFS 4.2, the NFS export is running on TrueNas core 12.0
I'll try to tweak my volume options to see if there's a diffenrence.

**Comment by rogerfar** [comment] 2021-01-13 18:58
I tried it here too and seeing the same issue:

![image](https://user-images.githubusercontent.com/1142915/104496737-98af1b00-5596-11eb-82d4-a95a220a560c.png)

When I'm normally getting 30MB/s+.

I'm not a docker expert by all means so if anyone has any optimization settings let me know!

**Comment by AlbanVidalenche** [comment] 2021-01-15 23:54
I tried again, and with the latest version of the container I am able to download at around 7MB/s.
I hope you'll be able to find the reason why the download is slow. The integration with Radarr is great and I would love to use RDT Client as my main download client.
I'll let you know if I find something relevant.

**Comment by rogerfar** [comment] 2021-01-19 15:29
I connected to the container `docker exec -it rdtclient /bin/bash` and ran the following speedtest:
```
apt-get install gnupg1 apt-transport-https dirmngr lsb-release
export INSTALL_KEY=379CE192D401AB61
export DEB_DISTRO=$(lsb_release -sc)
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $INSTALL_KEY
echo "deb https://ookla.bintray.com/debian ${DEB_DISTRO} main" | tee  /etc/apt/sources.list.d/speedtest.list
apt-get update
apt-get install speedtest
speedtest
```

This resulted in 
```
Latency:    11.16 ms   (0.56 ms jitter)
Download:   124.33 Mbps (data used: 179.9 MB)
Upload:    16.21 Mbps (data used: 13.8 MB)
Packet Loss:     0.0%
```

These are normal speeds, may be a little low for 300Mbit but much higher then the container can get. I wonder if there is an issue with .NET inside a container.

**Comment by timcoop3r** [comment] 2021-01-19 21:28
I'm not sure if it's related directly to the NFS issues, but I have been investigating an issue I see network side that seems to be related to a small TCP window size that could impact general download speeds.

I noticed it because the packets per-second rate is really high in the upload direction when downloading. In the range of 50% of the download packet rate. With a packet capture this seemed to confirm that TCP ACK is taking place for every couple of packets which is not expected behaviour. I would expect a much lower upload PPS rate than this, but I have not yet been able to establish the cause and I am still investigating. It would be helpful to know if you see this same behaviour in your container testing, and how this compares to outside a container or in a windows native environment?

**Comment by rogerfar** [comment] 2021-01-19 21:29
@timcoop3r I pushed a new container a few hours ago that has a buffersize of 64K, I wonder if that improves speeds.

**Comment by timcoop3r** [comment] 2021-01-19 21:43
I dont have a fast enough connection to test throughput but I can confirm that has had a significant impact in PPS rate.

Download PPS rate has reduced by half, and upload PPS rate is now only approx 25% of download rate. dotnet process CPU usage seems lower.
tcpdump shows download TCP window size (which would be controlled by the client side) has increased for me from 32 to 506 (KB?)
Based on that I would expect throughput to be higher with this newer build but can't confirm myself.

Where is the buffer set? Is this a dotnet thing or a container setting? Just curious how/why it may be impacting TCP behaviour   in this way as the OS would normally dynamically scale the TCP window size up and down in some way as required was my belief so is interesting effect.

**Comment by rogerfar** [comment] 2021-01-20 02:08
Buffer is set in the `DownloadClient`, it was 4k before but I upped it to 64k. I don't think that part has much to do with the container as the network stack is NATed so fairly transparent.

I'm just putting in some download and write speed tests to see where the bottleneck is exactly. RD has a speedtest file, but it's 10GB, so it takes quite a while to complete!

**Comment by AlbanVidalenche** [comment] 2021-01-20 09:57
With the lastest docker image, the download speed is now 10MB/s, it was 7MB/s before with my NFS setup.
Downloading directly to a local docker volume gives me 100MB/s, this is my maximum download speed at home.

**Comment by timcoop3r** [comment] 2021-01-20 10:19
@AlbanVidalenche can you run containers directly on the host that contain the NFS shares perhaps as a workaround?

**Comment by AlbanVidalenche** [comment] 2021-01-20 12:58
My NAS is a low budget TrueNas core, so docker would require a virtual machine and I don't have the resources to host it. I'll stick to this setup and hope for improvements in the future.

**Comment by rogerfar** [comment] 2021-01-20 17:42
I have made some more changes to the download handler, which is now using a download package instead. This now by default downloads with 8 threads and has support for speed limiting too.

In the Settings section I added some speed tests you can use.

So far speeds like a lot better, I'm getting a good 15MB/s here.

**Comment by timcoop3r** [comment] 2021-01-20 18:16
With the download speed test it runs for a few seconds then stops and reports the speed, just checking this is expected behaviour?

I still see massive upstream packets-per second so will investigate further into this

**Comment by timcoop3r** [comment] 2021-01-20 18:57
New downloader also seems to bypass container http proxy settings?
I see the API hits on the proxy, but not the file downloads as I was seeing previously. :(

**Comment by AlbanVidalenche** [comment] 2021-01-20 22:46
Just tried the new version and the speeds are great ! 
The download client's  behavior has changed, now the file is written directly into the container and then transferred to the NFS.
Basically it means that my container host must have sufficient space to download the file. Once the file is transferred it is removed from my container (nugget magic i guess).
This behavior is perfect for me, as downloading and writing to the NFS at the same time always saturate my CPU, causing big speed drops. My download speed are now 98MB/s for the download, and 106MB/s to the NFS.
Thank you very much

**Comment by rogerfar** [comment] 2021-01-20 22:49
I see yeah, the new Downloader accepts a temp directory parameter, now I also understand why there is a bit of lag after the download is complete, it's copying the file over.

I'll add a few more settings like, max download speed, temp directory and concurrent connections. But by default I'll probably make the temp directory a mapped path through docker mapping so other users won't run into space issues.

**Comment by AlbanVidalenche** [comment] 2021-01-20 22:59
Great, I guess the issue is solved, I'll close it if it's OK for you.

**Comment by timcoop3r** [comment] 2021-01-21 08:18
> I see yeah, the new Downloader accepts a temp directory parameter, now I also understand why there is a bit of lag after the download is complete, it's copying the file over.
> 
> I'll add a few more settings like, max download speed, temp directory and concurrent connections. But by default I'll probably make the temp directory a mapped path through docker mapping so other users won't run into space issues.

Be good to see if there is a way to have it write directly to the destination file and skip the temp directory, or at least make sure it can hardlink/move rather than copy if the paths are setup correctly to avoid unnecessary IO load when not required?

Also curious to see how a single stream performs, multiple streams shouldn’t normally be required. A modern machine should be able to saturate 1Gbit connection easily on a single stream if TCP is working properly 🤔 Maybe there is something else this downloaded is doing that also does things up other than the multiple streams 🤔

**Comment by rogerfar** [comment] 2021-01-21 14:32
It is doing a copy because it's a multi part downloader, but I will have a look in the [downloader](https://github.com/bezzad/Downloader) source to see if I can make a few improvements over how files are handled when you set the concurrency to 1.

**Comment by timcoop3r** [comment] 2021-01-21 14:58
> It is doing a copy because it's a multi part downloader, but I will have a look in the [downloader](https://github.com/bezzad/Downloader) source to see if I can make a few improvements over how files are handled when you set the concurrency to 1.

It's not the worst thing in the world with the multiple streams for it to be in a temp folder, similar to a traditional torrent, the key thing for me is that it tries to do a move operation rather than a copy, so if the temp location and final location are on the same filesystem it's not actually got any IO load to move the file and is an instant operation. A copy operation should only be required when its moving to another filesystem, like the NFS share example, where it can just update the pointer and it has to physically shift the file. If that makes sense?

The selectable concurrency thing is handy in other ways, if you can max out your connection with a single stream then it's probably less overhead and network congestion to have the single stream, then scale it up if you need more for more speed. Or to be able to reduce to one or two streams for other reasons I can't think of :)

**Comment by rogerfar** [comment] 2021-01-21 17:17
I'm not sure if this temp path in the container is a great idea, yes the download is nice and high but you still need to wait for all the chunks to be merged, which kinda voids the speed increase..

**Comment by timcoop3r** [comment] 2021-01-21 17:39
Arguably, the NFS speed problem was solved by the fact the data was cached locally first, then transferred to the NFS share, which could just as easily be achieved with the previous downloader code and an option for temporary storage or move when complete. Neither of which need to be inside the container itself if enabled.

Feels to me a bit like the multi-stream downloader was potentially just masking an issue with a single stream going faster, which should be possible if multiple streams can reach a given speed? Just still trying to figure out what/where that limitation might be.

**Comment by rogerfar** [comment] 2021-01-22 16:06
I have done some more testing and turns out I'm not a docker expert..

I have reverted back to the old downloader for simplicity, added 2 torrents in which download with OK speeds (10MB/s combined), but CPU pinned at 100% on my Ryzen 2700X with 32GB mem. I collected CPU traces with `dotnet-trace` and docker tooling but the application only uses like 5% CPU, the rest is all docker trying to write bits to the host (very high CPU on Vmmem). This is on a Windows docker host in Hyper-V.

I ran the application in a console on another much lower powered host (Intel G4560) on Windows and found it can download with the full 35MB/s with only 5% CPU.

@AlbanVidalenche do you see similar high CPU cycles when downloading a file?

I don't know if this is an issue that can be easily resolved, I found that other contains like `transmissions-openvpn` display similar behaviour when writing files.

**Comment by AlbanVidalenche** [comment] 2021-01-22 17:32
I pulled your latest image and tested.
My CPU is around 20%, and download speed is back to 10MB/s.

**Comment by timcoop3r** [comment] 2021-01-22 18:14
@rogerfar Are you testing with the disk write test or a normal download?

**Comment by rogerfar** [comment] 2021-01-22 18:16
Just a regular download from Sonarr.

**Comment by timcoop3r** [comment] 2021-01-22 18:33
Is the current published docker image the new or the old downloader? Just did a pull and it didn't seem to update?

With the current version and whatever downloader that is I see 25-30% total system load on an i3-7100, and 75% of that is the VPN client. So I'd say rdt-client is using less than 10% of total CPU on my system. This is maxing out my 76mbit connection at ~8MB/sec.

I could maybe update the hosts file to trick it to download the real-rebrid test file over the LAN if you have the URL?

**Comment by timcoop3r** [comment] 2021-01-22 18:45
Pretty sure I must be on the previous version, the image I have is from 3 days ago and it won't pull a new one for me yet. Not sure why.

**Comment by rogerfar** [comment] 2021-01-22 21:17
I had to re-push the images,  did that break something? Paths are still the same:
https://hub.docker.com/repository/docker/rogerfar/rdtclient

I just pushed it again to be sure.

**Comment by timcoop3r** [comment] 2021-01-22 21:50
That one pulled and clear difference in system load. rdt-client is now using double the CPU resources on this build compared to earlier.

**Comment by rogerfar** [comment] 2021-01-22 21:51
But does it also download twice as fast? ;)

**Comment by timcoop3r** [comment] 2021-01-22 21:53
> But does it also download twice as fast? ;)

lol, sadly not.

**Comment by rogerfar** [comment] 2021-01-22 21:57
I have done some more testing and I can't really put my finger on it. I have toned it down to as bare C# code as possible, but even then just using a simple `HttpClient` call gives high load, both in the container and on the host, so I'm not sure if the networking part in C# is very efficient in linux/docker.

I'm thinking to install `aria2c` on the container and use that to manage the downloads, it has an RPC API so should be doable.

**Comment by timcoop3r** [comment] 2021-01-23 13:18
So, just to confirm, the latest docker image now has the settings for temp folder and number of parallel streams etc, and is downloading to a temp file, does that sound right for what should be the latest version?

**Comment by rogerfar** [comment] 2021-01-23 17:41
That is correct yes. I have now pushed another image (amd64 only) that has both downloaders in it, you can switch between them in the settings.

**Comment by timcoop3r** [comment] 2021-01-23 20:39
Back on the simple downloader on the latest push, seeing the same high CPU now, dotnet about 38% of total capacity at 8MB/sec. (dotnet CPU usage '150%' reported by 'top' in linux, dual core with SMT). Can see why 15MB/sec would be a struggle.

**Comment by rogerfar** [comment] 2021-02-06 04:32
I have done some more testing and prototyping and I found a few things.

Aria2c downloader is a no go, it is very strict in how it handles downloads, especially TSL/SSL handshakes, and RealDebrid is not very strict. So lots of failed downloads and retries, and even so, I still have very high resource consumption.

I install the RDT client as a service on my Windows machine to compare performance and noticed this when I was downloading:

![image](https://user-images.githubusercontent.com/1142915/107108972-8b81f680-67f9-11eb-8d44-e312b542a5a5.png)

It's using the full bandwidth of 300Mbit but the disk itself can barely keep up and basically maxes out in write speed.

For now I'm keeping the 2 downloaders until a better solution comes to light.

**Closed by rogerfar** 2021-02-06 04:32 UTC
